### ISSUE TITLE
Cannot build project by source code download from github

### ISSUE THREAD

**Issue by hongsonitptit** [PhilJay/MPAndroidChart#1296]
Hi,
I am building MPAndroidChart project by source code from github. I download it as a zip file.
But when I imported it into eclipse, it notified that project cannot build because it could not find realm library. So, I searched realm library from internet and download it and add it as a library into project but it was still missed some file and cannot build.
The file that missed are: io.realm.dynamic.DynamicRealmObject
I really want to know what version of realm library that you used in this project is. 
Hope see your reply as soon as good!. 
Thanks you!

**Comment by hongsonitptit** [comment]
import io.realm.dynamic.DynamicRealmList;
import io.realm.dynamic.DynamicRealmObject;

It's exactly why I could not build done because it's could not find these classes

**Comment by Don2012** [comment]
Hi,
I got another error :
../MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
Error:(1425, 27) error: cannot find symbol method getYValueSum()
where T is a type-variable:
T extends ChartData<? extends DataSet<? extends Entry>> declared in class Chart
../MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
Error:(261, 29) error: cannot find symbol method getYValueSum()
where T is a type-variable:
T extends ChartData<? extends DataSet<? extends Entry>> declared in class Chart

**Comment by PhilJay** [comment]
@hongsonitptit: I have just pushed some fixes regarding your issue, please try again.

@Don2012: This method was removed since it was redundant. It is now only available for `PieChart` where it is needed. You can easily calculate your own sum by simply iterating over all values. That was what that method did.

**Comment by hongsonitptit** [comment]
@PhilJay : I still could not build done. It's shot screen when I do it.
![untitled](https://cloud.githubusercontent.com/assets/5134089/11916027/e7a2f5e2-a6f5-11e5-8fdd-46e87898ae25.png)
You used realm library into this project but I can not see the build path or reference link to realm library. May be you forgot add it into this project???

**Comment by Don2012** [comment]
@PhilJay Thanks for your answer.

**Comment by hongsonitptit** [comment]
Anyone help me???

**Comment by PhilJay** [comment]
Okay now that you posted the screenshot I see where your issue is.

 - Problem: This project now has an optional gradle dependency to realm

So basically if your IDE does not support gradle or you are not building your project with gradle, you will have the build errors mentioned above.

You have two options:

 - Build your project with gradle
 - Remove all files that produce build errors from the library (those files are only related to plotting data directly from realm.io database and will not be needed for normal use of the library)
