### ISSUE TITLE
 Failed to resolve:com.github.PhilJay:MPAndroidChart:v2.2.5

### ISSUE THREAD

**Issue by patelanil2007** [PhilJay/MPAndroidChart#1918]

**Comment by patelanil2007** [comment]
why u closed without specification. its not working

**Comment by PhilJay** [comment]
Because I spent about as much time as you did on resolving the issue.

 - https://github.com/PhilJay/MPAndroidChart#questions--issues
 - Is your build.gradle file setup correctly?
 - Did you reference the jitpack repository?
 - Did you search for your issue on google / stackoverflow?

**Comment by patelanil2007** [comment]
its not working man

**Comment by pfives** [comment]
@patelanil2007 you are providing no other information other than it is not working. How is he supposed to help you? 

You probably added jitpack.io to the wrong section of your project build.gradle see: http://stackoverflow.com/questions/32718820/failed-to-resolve-com-github-philjaympandroidchartv2-1-4

**Comment by patelanil2007** [comment]
@pfives  i have added below code in app's Build.gradle

> repositories {
    maven { url "https://jitpack.io" }
}

>  compile 'com.github.PhilJay:MPAndroidChart:v2.1.6'}

got below error

> Error:(31, 13) Failed to resolve: com.github.PhilJay:MPAndroidChart:v2.1.6

i try to find lib from Library Dependency but can't find

**Comment by pfives** [comment]
@patelanil2007 that is still not enough context. You need to have it under your allprojects script in your top level build.gradle.

`buildscript {
    repositories {
        jcenter()
        maven{
            url "https://plugins.gradle.org/m2/"
        }
    }

}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
`

**Comment by kfwong** [comment]
Just in case someone still having the similar issue:

I had this problem even though I set the jitpack.io url to the appropriate section in my build.gradle, as many closed issues I found having the same old replies, but none are working for me.

The problem lies with the ```gradle-wrapper.properties```, you probably have to change the distribution url to the latest, in my case 2.10 to 2.14.1. 

```gradle
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
```

Ref:
http://stackoverflow.com/questions/33058358/jitpack-io-failed-to-resolve-github-repo

**Comment by ps06756** [comment]
I am having the same problem, changing the distribution url in `grade-wrapper.properties`, also doesn't work for me.

**Comment by amanshuraikwar** [comment]
Same problem for me, no solution is working!

**Comment by luowei428** [comment]
@pfives 's comments worked. I just fixed my problem.

**Comment by harshalyeole-tudip** [comment]
Not working for me too

**Comment by phuwin** [comment]
If you have multiple maven repositories, do it like this
```
repositories {
    jcenter()
    maven { url "https://maven.java.net/content/groups/public/" }
    maven { url "https://jitpack.io" }
}
```

**Comment by nirwannursabda** [comment]
Believe it or not

Im changing URL from maven { url "https://www.jitpack.io" }
into 
maven { url "https://jitpack.io" }

Now its working, what happen with triple www
Strange i think

**Comment by billrancho** [comment]
for ones who still have this issue. You will need to separate jitpack and maven repos into buildscript and all project repositories.
It should look like
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

it works fine for me.
Cheers mates.

**Comment by ayetolusamuel** [comment]
Nice work Dude.

**Comment by azisoli** [comment]
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.3.

Could not get resource 'https://jcenter.bintray.com/com/github/PhilJay/MPAndroidChart/v3.0.3/MPAndroidChart-v3.0.3.pom'.

problem is that when i put this address in chorom https://jcenter.bintray.com/com/github/PhilJay/MPAndroidChart
there is no response actually there is PhilJay/XXX/  BUT THERE IS NO PhilJay/MPAndroidChart

**Comment by parveenpjpt** [comment]
I have getting same issue  i have just put the version name like this:

compile 'com.github.kittinunf.fuel:fuel:1.12.0' //for JVM
    compile 'com.github.kittinunf.fuel:fuel-android:1.12.0' //for Android
    compile 'com.github.kittinunf.fuel:fuel-livedata:1.12.0' //for LiveData support
    compile 'com.github.kittinunf.fuel:fuel-rxjava:1.12.0' //for RxJava support
    compile 'com.github.kittinunf.fuel:fuel-gson:1.12.0' //for Gson support
    compile 'com.github.kittinunf.fuel:fuel-jackson:1.12.0' //for Jackson support
    compile 'com.github.kittinunf.fuel:fuel-moshi:1.12.0' //for Moshi support

And it will Resolve.

Reagrd 
Parveen Prajapati

**Comment by anilthummar** [comment]
Please add below code in gradle file:

repositories {
jcenter()
maven { url "https://jitpack.io" }
}
dependencies {
  
    implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'

}

**Comment by thisalwijayakumara** [comment]
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'

}

Its not working

**Comment by vishalsgithub** [comment]
i have solve this isssue by disable the Gradle offline work in settings.

Go to File>Setting>Gradle  Disable Offline Work ,
and try again

**Comment by dhirendrakumarsinghlakhan** [comment]
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'
   
}

its working

**Comment by SWAT10101** [comment]
> @patelanil2007 that is still not enough context. You need to have it under your allprojects script in your top level build.gradle.
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         maven { url "https://jitpack.io" }
>     }
> 
> }
> 
> allprojects {
>     repositories {
>         jcenter()
>         maven { url "https://jitpack.io" }
>     }
> }
> ```

it is work on android studio 3.4

**Comment by Sanaebadi97** [comment]
https://stackoverflow.com/a/37892027/10699119

this link save my life

**Comment by RabbitCorp** [comment]
Yeah, its working for me, 
1. You need the 3.0 version of Gradle or later(file: gradle-wrapper.properties )
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`
2. In tour gradle.build (Module:Project:)
```
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
3.In tour gradle.build (Module:app)
`implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0-alpha'`
4.Profit

**Comment by Tabletin** [comment]
I had the same problem, but it  was solved adding:

buildscript {
    repositories {
        google()
        jcenter()
        maven {url 'https://jitpack.io'}
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}


Thanks, Phil Jay for this amazing library :+1:

**Comment by VictorKabata** [comment]
> Because I spent about as much time as you did on resolving the issue.
> 
> * https://github.com/PhilJay/MPAndroidChart#questions--issues
> * Is your build.gradle file setup correctly?
> * Did you reference the jitpack repository?
> * Did you search for your issue on google / stackoverflow?
> 
> I just tested resolving v2.2.5 on a demo project, it worked just fine. Without any further information I have absolutely no idea why it's not working for you.

Update the readme to show exactly where to place maven { url 'https://jitpack.io' }

**Comment by Licmeth** [comment]
With a new project and an empty Activity in Android Studio, I needed to add maven {url 'https://jitpack.io'} to settings.gradle
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by shreyas1g** [comment]
![Untitled](https://user-images.githubusercontent.com/68431059/131452926-f98a48a6-8e55-4dbd-9c82-f9cbaa4fb5ff.png)
![Untitled1](https://user-images.githubusercontent.com/68431059/131452931-88cf82d6-eac5-4b40-af3a-ed7ceec05c57.png)


tryed all possible solutions still getting 
![Uploading Untitled2.png…]()

**Comment by shreyas1g** [comment]
Failed to resolve resolve:com.github.PhilJay:MPAndroidChart:v3.1.0

im using android studio version 2020.3.1

**Comment by frestoinc** [comment]
> Failed to resolve resolve:com.github.PhilJay:MPAndroidChart:v3.1.0
> 
> im using android studio version 2020.3.1

Add it in your settings.gradle

`dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}`

**Comment by truedem** [comment]
5 years later and this thing is still here (and no solutions work)

**Comment by teyteymey** [comment]
> > Failed to resolve resolve:com.github.PhilJay:MPAndroidChart:v3.1.0
> > im using android studio version 2020.3.1
> 
> Add it in your settings.gradle
> 
> `dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) repositories { google() mavenCentral() maven { url "https://jitpack.io" } } }`

For some reason this worked. I think it was putting the maven url in settings.gradle.
Also, instead of FAIL_ON_PROJECT_REPOS I had to put PREFER_SETTINGS.

**Comment by truedem** [comment]
In my 7 years Android practice this is the first library which required editing settings.gradle

**Comment by HectorS123** [comment]
> > > No se pudo resolver resolve:com.github.PhilJay:MPAndroidChart:v3.1.0 Estoy 
> > > usando la versión 2020.3.1 de Android Studio
> > 
> > 
> > Agrégalo en tu configuración.gradle
> > `dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) repositories { google() mavenCentral() maven { url "https://jitpack.io" } } }`
> 
> Por alguna razón esto funcionó. Creo que estaba poniendo la URL de maven en settings.gradle. Además, en lugar de FAIL_ON_PROJECT_REPOS tuve que poner PREFER_SETTINGS.


Perfect function.
Thanks

**Comment by sarvarmasharipov72** [comment]
I also have this problem but I did this added maven { url 'https://jitpack.io' } settings.gradle
![image](https://user-images.githubusercontent.com/63916119/151920112-448ff954-bbba-4c94-b876-ea9000d8d141.png)

**Comment by Noah-Mn** [comment]
It finally worked for me as well 

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
